# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libaroma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libaroma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all:
	@./src/aroma_build.sh 1200 "libaroma"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libaroma_test

# Build rule for target.
libaroma_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libaroma_test
.PHONY : libaroma_test

# fast build rule for target.
libaroma_test/fast:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/build
.PHONY : libaroma_test/fast

#=============================================================================
# Target rules for targets named aroma

# Build rule for target.
aroma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aroma
.PHONY : aroma

# fast build rule for target.
aroma/fast:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/build
.PHONY : aroma/fast

#=============================================================================
# Target rules for targets named z

# Build rule for target.
z : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 z
.PHONY : z

# fast build rule for target.
z/fast:
	$(MAKE) -f libs/zlib/CMakeFiles/z.dir/build.make libs/zlib/CMakeFiles/z.dir/build
.PHONY : z/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) -f libs/freetype/CMakeFiles/freetype.dir/build.make libs/freetype/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named harfbuzz

# Build rule for target.
harfbuzz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harfbuzz
.PHONY : harfbuzz

# fast build rule for target.
harfbuzz/fast:
	$(MAKE) -f libs/harfbuzz-ng/CMakeFiles/harfbuzz.dir/build.make libs/harfbuzz-ng/CMakeFiles/harfbuzz.dir/build
.PHONY : harfbuzz/fast

#=============================================================================
# Target rules for targets named hbucdn

# Build rule for target.
hbucdn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hbucdn
.PHONY : hbucdn

# fast build rule for target.
hbucdn/fast:
	$(MAKE) -f libs/harfbuzz-ng/src/hb-ucdn/CMakeFiles/hbucdn.dir/build.make libs/harfbuzz-ng/src/hb-ucdn/CMakeFiles/hbucdn.dir/build
.PHONY : hbucdn/fast

#=============================================================================
# Target rules for targets named minzip

# Build rule for target.
minzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minzip
.PHONY : minzip

# fast build rule for target.
minzip/fast:
	$(MAKE) -f libs/minzip/CMakeFiles/minzip.dir/build.make libs/minzip/CMakeFiles/minzip.dir/build
.PHONY : minzip/fast

#=============================================================================
# Target rules for targets named png

# Build rule for target.
png: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 png
.PHONY : png

# fast build rule for target.
png/fast:
	$(MAKE) -f libs/png/CMakeFiles/png.dir/build.make libs/png/CMakeFiles/png.dir/build
.PHONY : png/fast

#=============================================================================
# Target rules for targets named jpeg

# Build rule for target.
jpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpeg
.PHONY : jpeg

# fast build rule for target.
jpeg/fast:
	$(MAKE) -f libs/jpeg/CMakeFiles/jpeg.dir/build.make libs/jpeg/CMakeFiles/jpeg.dir/build
.PHONY : jpeg/fast

examples/recovery/recovery.o: examples/recovery/recovery.c.o

.PHONY : examples/recovery/recovery.o

# target to build an object file
examples/recovery/recovery.c.o:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery.c.o
.PHONY : examples/recovery/recovery.c.o

examples/recovery/recovery.i: examples/recovery/recovery.c.i

.PHONY : examples/recovery/recovery.i

# target to preprocess a source file
examples/recovery/recovery.c.i:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery.c.i
.PHONY : examples/recovery/recovery.c.i

examples/recovery/recovery.s: examples/recovery/recovery.c.s

.PHONY : examples/recovery/recovery.s

# target to generate assembly for a file
examples/recovery/recovery.c.s:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery.c.s
.PHONY : examples/recovery/recovery.c.s

examples/recovery/recovery_libs.o: examples/recovery/recovery_libs.c.o

.PHONY : examples/recovery/recovery_libs.o

# target to build an object file
examples/recovery/recovery_libs.c.o:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_libs.c.o
.PHONY : examples/recovery/recovery_libs.c.o

examples/recovery/recovery_libs.i: examples/recovery/recovery_libs.c.i

.PHONY : examples/recovery/recovery_libs.i

# target to preprocess a source file
examples/recovery/recovery_libs.c.i:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_libs.c.i
.PHONY : examples/recovery/recovery_libs.c.i

examples/recovery/recovery_libs.s: examples/recovery/recovery_libs.c.s

.PHONY : examples/recovery/recovery_libs.s

# target to generate assembly for a file
examples/recovery/recovery_libs.c.s:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_libs.c.s
.PHONY : examples/recovery/recovery_libs.c.s

examples/recovery/recovery_mainmenu.o: examples/recovery/recovery_mainmenu.c.o

.PHONY : examples/recovery/recovery_mainmenu.o

# target to build an object file
examples/recovery/recovery_mainmenu.c.o:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_mainmenu.c.o
.PHONY : examples/recovery/recovery_mainmenu.c.o

examples/recovery/recovery_mainmenu.i: examples/recovery/recovery_mainmenu.c.i

.PHONY : examples/recovery/recovery_mainmenu.i

# target to preprocess a source file
examples/recovery/recovery_mainmenu.c.i:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_mainmenu.c.i
.PHONY : examples/recovery/recovery_mainmenu.c.i

examples/recovery/recovery_mainmenu.s: examples/recovery/recovery_mainmenu.c.s

.PHONY : examples/recovery/recovery_mainmenu.s

# target to generate assembly for a file
examples/recovery/recovery_mainmenu.c.s:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_mainmenu.c.s
.PHONY : examples/recovery/recovery_mainmenu.c.s

examples/recovery/recovery_usb.o: examples/recovery/recovery_usb.c.o

.PHONY : examples/recovery/recovery_usb.o

# target to build an object file
examples/recovery/recovery_usb.c.o:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_usb.c.o
.PHONY : examples/recovery/recovery_usb.c.o

examples/recovery/recovery_usb.i: examples/recovery/recovery_usb.c.i

.PHONY : examples/recovery/recovery_usb.i

# target to preprocess a source file
examples/recovery/recovery_usb.c.i:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_usb.c.i
.PHONY : examples/recovery/recovery_usb.c.i

examples/recovery/recovery_usb.s: examples/recovery/recovery_usb.c.s

.PHONY : examples/recovery/recovery_usb.s

# target to generate assembly for a file
examples/recovery/recovery_usb.c.s:
	$(MAKE) -f CMakeFiles/libaroma_test.dir/build.make CMakeFiles/libaroma_test.dir/examples/recovery/recovery_usb.c.s
.PHONY : examples/recovery/recovery_usb.c.s

src/aroma/arch/x86_64/android_memset16.o: src/aroma/arch/x86_64/android_memset16.S.o

.PHONY : src/aroma/arch/x86_64/android_memset16.o

# target to build an object file
src/aroma/arch/x86_64/android_memset16.S.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/arch/x86_64/android_memset16.S.o
.PHONY : src/aroma/arch/x86_64/android_memset16.S.o

src/aroma/arch/x86_64/android_memset32.o: src/aroma/arch/x86_64/android_memset32.S.o

.PHONY : src/aroma/arch/x86_64/android_memset32.o

# target to build an object file
src/aroma/arch/x86_64/android_memset32.S.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/arch/x86_64/android_memset32.S.o
.PHONY : src/aroma/arch/x86_64/android_memset32.S.o

src/aroma/aroma.o: src/aroma/aroma.c.o

.PHONY : src/aroma/aroma.o

# target to build an object file
src/aroma/aroma.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/aroma.c.o
.PHONY : src/aroma/aroma.c.o

src/aroma/aroma.i: src/aroma/aroma.c.i

.PHONY : src/aroma/aroma.i

# target to preprocess a source file
src/aroma/aroma.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/aroma.c.i
.PHONY : src/aroma/aroma.c.i

src/aroma/aroma.s: src/aroma/aroma.c.s

.PHONY : src/aroma/aroma.s

# target to generate assembly for a file
src/aroma/aroma.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/aroma.c.s
.PHONY : src/aroma/aroma.c.s

src/aroma/controls/ctl_bar.o: src/aroma/controls/ctl_bar.c.o

.PHONY : src/aroma/controls/ctl_bar.o

# target to build an object file
src/aroma/controls/ctl_bar.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_bar.c.o
.PHONY : src/aroma/controls/ctl_bar.c.o

src/aroma/controls/ctl_bar.i: src/aroma/controls/ctl_bar.c.i

.PHONY : src/aroma/controls/ctl_bar.i

# target to preprocess a source file
src/aroma/controls/ctl_bar.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_bar.c.i
.PHONY : src/aroma/controls/ctl_bar.c.i

src/aroma/controls/ctl_bar.s: src/aroma/controls/ctl_bar.c.s

.PHONY : src/aroma/controls/ctl_bar.s

# target to generate assembly for a file
src/aroma/controls/ctl_bar.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_bar.c.s
.PHONY : src/aroma/controls/ctl_bar.c.s

src/aroma/controls/ctl_button.o: src/aroma/controls/ctl_button.c.o

.PHONY : src/aroma/controls/ctl_button.o

# target to build an object file
src/aroma/controls/ctl_button.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_button.c.o
.PHONY : src/aroma/controls/ctl_button.c.o

src/aroma/controls/ctl_button.i: src/aroma/controls/ctl_button.c.i

.PHONY : src/aroma/controls/ctl_button.i

# target to preprocess a source file
src/aroma/controls/ctl_button.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_button.c.i
.PHONY : src/aroma/controls/ctl_button.c.i

src/aroma/controls/ctl_button.s: src/aroma/controls/ctl_button.c.s

.PHONY : src/aroma/controls/ctl_button.s

# target to generate assembly for a file
src/aroma/controls/ctl_button.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_button.c.s
.PHONY : src/aroma/controls/ctl_button.c.s

src/aroma/controls/ctl_fragment.o: src/aroma/controls/ctl_fragment.c.o

.PHONY : src/aroma/controls/ctl_fragment.o

# target to build an object file
src/aroma/controls/ctl_fragment.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_fragment.c.o
.PHONY : src/aroma/controls/ctl_fragment.c.o

src/aroma/controls/ctl_fragment.i: src/aroma/controls/ctl_fragment.c.i

.PHONY : src/aroma/controls/ctl_fragment.i

# target to preprocess a source file
src/aroma/controls/ctl_fragment.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_fragment.c.i
.PHONY : src/aroma/controls/ctl_fragment.c.i

src/aroma/controls/ctl_fragment.s: src/aroma/controls/ctl_fragment.c.s

.PHONY : src/aroma/controls/ctl_fragment.s

# target to generate assembly for a file
src/aroma/controls/ctl_fragment.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_fragment.c.s
.PHONY : src/aroma/controls/ctl_fragment.c.s

src/aroma/controls/ctl_image.o: src/aroma/controls/ctl_image.c.o

.PHONY : src/aroma/controls/ctl_image.o

# target to build an object file
src/aroma/controls/ctl_image.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_image.c.o
.PHONY : src/aroma/controls/ctl_image.c.o

src/aroma/controls/ctl_image.i: src/aroma/controls/ctl_image.c.i

.PHONY : src/aroma/controls/ctl_image.i

# target to preprocess a source file
src/aroma/controls/ctl_image.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_image.c.i
.PHONY : src/aroma/controls/ctl_image.c.i

src/aroma/controls/ctl_image.s: src/aroma/controls/ctl_image.c.s

.PHONY : src/aroma/controls/ctl_image.s

# target to generate assembly for a file
src/aroma/controls/ctl_image.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_image.c.s
.PHONY : src/aroma/controls/ctl_image.c.s

src/aroma/controls/ctl_label.o: src/aroma/controls/ctl_label.c.o

.PHONY : src/aroma/controls/ctl_label.o

# target to build an object file
src/aroma/controls/ctl_label.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_label.c.o
.PHONY : src/aroma/controls/ctl_label.c.o

src/aroma/controls/ctl_label.i: src/aroma/controls/ctl_label.c.i

.PHONY : src/aroma/controls/ctl_label.i

# target to preprocess a source file
src/aroma/controls/ctl_label.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_label.c.i
.PHONY : src/aroma/controls/ctl_label.c.i

src/aroma/controls/ctl_label.s: src/aroma/controls/ctl_label.c.s

.PHONY : src/aroma/controls/ctl_label.s

# target to generate assembly for a file
src/aroma/controls/ctl_label.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_label.c.s
.PHONY : src/aroma/controls/ctl_label.c.s

src/aroma/controls/ctl_list.o: src/aroma/controls/ctl_list.c.o

.PHONY : src/aroma/controls/ctl_list.o

# target to build an object file
src/aroma/controls/ctl_list.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_list.c.o
.PHONY : src/aroma/controls/ctl_list.c.o

src/aroma/controls/ctl_list.i: src/aroma/controls/ctl_list.c.i

.PHONY : src/aroma/controls/ctl_list.i

# target to preprocess a source file
src/aroma/controls/ctl_list.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_list.c.i
.PHONY : src/aroma/controls/ctl_list.c.i

src/aroma/controls/ctl_list.s: src/aroma/controls/ctl_list.c.s

.PHONY : src/aroma/controls/ctl_list.s

# target to generate assembly for a file
src/aroma/controls/ctl_list.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_list.c.s
.PHONY : src/aroma/controls/ctl_list.c.s

src/aroma/controls/ctl_pager.o: src/aroma/controls/ctl_pager.c.o

.PHONY : src/aroma/controls/ctl_pager.o

# target to build an object file
src/aroma/controls/ctl_pager.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_pager.c.o
.PHONY : src/aroma/controls/ctl_pager.c.o

src/aroma/controls/ctl_pager.i: src/aroma/controls/ctl_pager.c.i

.PHONY : src/aroma/controls/ctl_pager.i

# target to preprocess a source file
src/aroma/controls/ctl_pager.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_pager.c.i
.PHONY : src/aroma/controls/ctl_pager.c.i

src/aroma/controls/ctl_pager.s: src/aroma/controls/ctl_pager.c.s

.PHONY : src/aroma/controls/ctl_pager.s

# target to generate assembly for a file
src/aroma/controls/ctl_pager.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_pager.c.s
.PHONY : src/aroma/controls/ctl_pager.c.s

src/aroma/controls/ctl_progress.o: src/aroma/controls/ctl_progress.c.o

.PHONY : src/aroma/controls/ctl_progress.o

# target to build an object file
src/aroma/controls/ctl_progress.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_progress.c.o
.PHONY : src/aroma/controls/ctl_progress.c.o

src/aroma/controls/ctl_progress.i: src/aroma/controls/ctl_progress.c.i

.PHONY : src/aroma/controls/ctl_progress.i

# target to preprocess a source file
src/aroma/controls/ctl_progress.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_progress.c.i
.PHONY : src/aroma/controls/ctl_progress.c.i

src/aroma/controls/ctl_progress.s: src/aroma/controls/ctl_progress.c.s

.PHONY : src/aroma/controls/ctl_progress.s

# target to generate assembly for a file
src/aroma/controls/ctl_progress.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_progress.c.s
.PHONY : src/aroma/controls/ctl_progress.c.s

src/aroma/controls/ctl_scroll.o: src/aroma/controls/ctl_scroll.c.o

.PHONY : src/aroma/controls/ctl_scroll.o

# target to build an object file
src/aroma/controls/ctl_scroll.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_scroll.c.o
.PHONY : src/aroma/controls/ctl_scroll.c.o

src/aroma/controls/ctl_scroll.i: src/aroma/controls/ctl_scroll.c.i

.PHONY : src/aroma/controls/ctl_scroll.i

# target to preprocess a source file
src/aroma/controls/ctl_scroll.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_scroll.c.i
.PHONY : src/aroma/controls/ctl_scroll.c.i

src/aroma/controls/ctl_scroll.s: src/aroma/controls/ctl_scroll.c.s

.PHONY : src/aroma/controls/ctl_scroll.s

# target to generate assembly for a file
src/aroma/controls/ctl_scroll.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_scroll.c.s
.PHONY : src/aroma/controls/ctl_scroll.c.s

src/aroma/controls/ctl_tabs.o: src/aroma/controls/ctl_tabs.c.o

.PHONY : src/aroma/controls/ctl_tabs.o

# target to build an object file
src/aroma/controls/ctl_tabs.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_tabs.c.o
.PHONY : src/aroma/controls/ctl_tabs.c.o

src/aroma/controls/ctl_tabs.i: src/aroma/controls/ctl_tabs.c.i

.PHONY : src/aroma/controls/ctl_tabs.i

# target to preprocess a source file
src/aroma/controls/ctl_tabs.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_tabs.c.i
.PHONY : src/aroma/controls/ctl_tabs.c.i

src/aroma/controls/ctl_tabs.s: src/aroma/controls/ctl_tabs.c.s

.PHONY : src/aroma/controls/ctl_tabs.s

# target to generate assembly for a file
src/aroma/controls/ctl_tabs.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/ctl_tabs.c.s
.PHONY : src/aroma/controls/ctl_tabs.c.s

src/aroma/controls/listitem/listitem_caption.o: src/aroma/controls/listitem/listitem_caption.c.o

.PHONY : src/aroma/controls/listitem/listitem_caption.o

# target to build an object file
src/aroma/controls/listitem/listitem_caption.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_caption.c.o
.PHONY : src/aroma/controls/listitem/listitem_caption.c.o

src/aroma/controls/listitem/listitem_caption.i: src/aroma/controls/listitem/listitem_caption.c.i

.PHONY : src/aroma/controls/listitem/listitem_caption.i

# target to preprocess a source file
src/aroma/controls/listitem/listitem_caption.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_caption.c.i
.PHONY : src/aroma/controls/listitem/listitem_caption.c.i

src/aroma/controls/listitem/listitem_caption.s: src/aroma/controls/listitem/listitem_caption.c.s

.PHONY : src/aroma/controls/listitem/listitem_caption.s

# target to generate assembly for a file
src/aroma/controls/listitem/listitem_caption.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_caption.c.s
.PHONY : src/aroma/controls/listitem/listitem_caption.c.s

src/aroma/controls/listitem/listitem_check.o: src/aroma/controls/listitem/listitem_check.c.o

.PHONY : src/aroma/controls/listitem/listitem_check.o

# target to build an object file
src/aroma/controls/listitem/listitem_check.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_check.c.o
.PHONY : src/aroma/controls/listitem/listitem_check.c.o

src/aroma/controls/listitem/listitem_check.i: src/aroma/controls/listitem/listitem_check.c.i

.PHONY : src/aroma/controls/listitem/listitem_check.i

# target to preprocess a source file
src/aroma/controls/listitem/listitem_check.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_check.c.i
.PHONY : src/aroma/controls/listitem/listitem_check.c.i

src/aroma/controls/listitem/listitem_check.s: src/aroma/controls/listitem/listitem_check.c.s

.PHONY : src/aroma/controls/listitem/listitem_check.s

# target to generate assembly for a file
src/aroma/controls/listitem/listitem_check.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_check.c.s
.PHONY : src/aroma/controls/listitem/listitem_check.c.s

src/aroma/controls/listitem/listitem_divider.o: src/aroma/controls/listitem/listitem_divider.c.o

.PHONY : src/aroma/controls/listitem/listitem_divider.o

# target to build an object file
src/aroma/controls/listitem/listitem_divider.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_divider.c.o
.PHONY : src/aroma/controls/listitem/listitem_divider.c.o

src/aroma/controls/listitem/listitem_divider.i: src/aroma/controls/listitem/listitem_divider.c.i

.PHONY : src/aroma/controls/listitem/listitem_divider.i

# target to preprocess a source file
src/aroma/controls/listitem/listitem_divider.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_divider.c.i
.PHONY : src/aroma/controls/listitem/listitem_divider.c.i

src/aroma/controls/listitem/listitem_divider.s: src/aroma/controls/listitem/listitem_divider.c.s

.PHONY : src/aroma/controls/listitem/listitem_divider.s

# target to generate assembly for a file
src/aroma/controls/listitem/listitem_divider.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_divider.c.s
.PHONY : src/aroma/controls/listitem/listitem_divider.c.s

src/aroma/controls/listitem/listitem_image.o: src/aroma/controls/listitem/listitem_image.c.o

.PHONY : src/aroma/controls/listitem/listitem_image.o

# target to build an object file
src/aroma/controls/listitem/listitem_image.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_image.c.o
.PHONY : src/aroma/controls/listitem/listitem_image.c.o

src/aroma/controls/listitem/listitem_image.i: src/aroma/controls/listitem/listitem_image.c.i

.PHONY : src/aroma/controls/listitem/listitem_image.i

# target to preprocess a source file
src/aroma/controls/listitem/listitem_image.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_image.c.i
.PHONY : src/aroma/controls/listitem/listitem_image.c.i

src/aroma/controls/listitem/listitem_image.s: src/aroma/controls/listitem/listitem_image.c.s

.PHONY : src/aroma/controls/listitem/listitem_image.s

# target to generate assembly for a file
src/aroma/controls/listitem/listitem_image.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_image.c.s
.PHONY : src/aroma/controls/listitem/listitem_image.c.s

src/aroma/controls/listitem/listitem_menu.o: src/aroma/controls/listitem/listitem_menu.c.o

.PHONY : src/aroma/controls/listitem/listitem_menu.o

# target to build an object file
src/aroma/controls/listitem/listitem_menu.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_menu.c.o
.PHONY : src/aroma/controls/listitem/listitem_menu.c.o

src/aroma/controls/listitem/listitem_menu.i: src/aroma/controls/listitem/listitem_menu.c.i

.PHONY : src/aroma/controls/listitem/listitem_menu.i

# target to preprocess a source file
src/aroma/controls/listitem/listitem_menu.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_menu.c.i
.PHONY : src/aroma/controls/listitem/listitem_menu.c.i

src/aroma/controls/listitem/listitem_menu.s: src/aroma/controls/listitem/listitem_menu.c.s

.PHONY : src/aroma/controls/listitem/listitem_menu.s

# target to generate assembly for a file
src/aroma/controls/listitem/listitem_menu.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_menu.c.s
.PHONY : src/aroma/controls/listitem/listitem_menu.c.s

src/aroma/controls/listitem/listitem_option.o: src/aroma/controls/listitem/listitem_option.c.o

.PHONY : src/aroma/controls/listitem/listitem_option.o

# target to build an object file
src/aroma/controls/listitem/listitem_option.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_option.c.o
.PHONY : src/aroma/controls/listitem/listitem_option.c.o

src/aroma/controls/listitem/listitem_option.i: src/aroma/controls/listitem/listitem_option.c.i

.PHONY : src/aroma/controls/listitem/listitem_option.i

# target to preprocess a source file
src/aroma/controls/listitem/listitem_option.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_option.c.i
.PHONY : src/aroma/controls/listitem/listitem_option.c.i

src/aroma/controls/listitem/listitem_option.s: src/aroma/controls/listitem/listitem_option.c.s

.PHONY : src/aroma/controls/listitem/listitem_option.s

# target to generate assembly for a file
src/aroma/controls/listitem/listitem_option.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/controls/listitem/listitem_option.c.s
.PHONY : src/aroma/controls/listitem/listitem_option.c.s

src/aroma/debug/compiler_message.o: src/aroma/debug/compiler_message.c.o

.PHONY : src/aroma/debug/compiler_message.o

# target to build an object file
src/aroma/debug/compiler_message.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/debug/compiler_message.c.o
.PHONY : src/aroma/debug/compiler_message.c.o

src/aroma/debug/compiler_message.i: src/aroma/debug/compiler_message.c.i

.PHONY : src/aroma/debug/compiler_message.i

# target to preprocess a source file
src/aroma/debug/compiler_message.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/debug/compiler_message.c.i
.PHONY : src/aroma/debug/compiler_message.c.i

src/aroma/debug/compiler_message.s: src/aroma/debug/compiler_message.c.s

.PHONY : src/aroma/debug/compiler_message.s

# target to generate assembly for a file
src/aroma/debug/compiler_message.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/debug/compiler_message.c.s
.PHONY : src/aroma/debug/compiler_message.c.s

src/aroma/debug/memory_tracking.o: src/aroma/debug/memory_tracking.c.o

.PHONY : src/aroma/debug/memory_tracking.o

# target to build an object file
src/aroma/debug/memory_tracking.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/debug/memory_tracking.c.o
.PHONY : src/aroma/debug/memory_tracking.c.o

src/aroma/debug/memory_tracking.i: src/aroma/debug/memory_tracking.c.i

.PHONY : src/aroma/debug/memory_tracking.i

# target to preprocess a source file
src/aroma/debug/memory_tracking.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/debug/memory_tracking.c.i
.PHONY : src/aroma/debug/memory_tracking.c.i

src/aroma/debug/memory_tracking.s: src/aroma/debug/memory_tracking.c.s

.PHONY : src/aroma/debug/memory_tracking.s

# target to generate assembly for a file
src/aroma/debug/memory_tracking.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/debug/memory_tracking.c.s
.PHONY : src/aroma/debug/memory_tracking.c.s

src/aroma/graph/artworker.o: src/aroma/graph/artworker.c.o

.PHONY : src/aroma/graph/artworker.o

# target to build an object file
src/aroma/graph/artworker.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/artworker.c.o
.PHONY : src/aroma/graph/artworker.c.o

src/aroma/graph/artworker.i: src/aroma/graph/artworker.c.i

.PHONY : src/aroma/graph/artworker.i

# target to preprocess a source file
src/aroma/graph/artworker.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/artworker.c.i
.PHONY : src/aroma/graph/artworker.c.i

src/aroma/graph/artworker.s: src/aroma/graph/artworker.c.s

.PHONY : src/aroma/graph/artworker.s

# target to generate assembly for a file
src/aroma/graph/artworker.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/artworker.c.s
.PHONY : src/aroma/graph/artworker.c.s

src/aroma/graph/canvas.o: src/aroma/graph/canvas.c.o

.PHONY : src/aroma/graph/canvas.o

# target to build an object file
src/aroma/graph/canvas.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/canvas.c.o
.PHONY : src/aroma/graph/canvas.c.o

src/aroma/graph/canvas.i: src/aroma/graph/canvas.c.i

.PHONY : src/aroma/graph/canvas.i

# target to preprocess a source file
src/aroma/graph/canvas.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/canvas.c.i
.PHONY : src/aroma/graph/canvas.c.i

src/aroma/graph/canvas.s: src/aroma/graph/canvas.c.s

.PHONY : src/aroma/graph/canvas.s

# target to generate assembly for a file
src/aroma/graph/canvas.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/canvas.c.s
.PHONY : src/aroma/graph/canvas.c.s

src/aroma/graph/draw/blur.o: src/aroma/graph/draw/blur.c.o

.PHONY : src/aroma/graph/draw/blur.o

# target to build an object file
src/aroma/graph/draw/blur.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/blur.c.o
.PHONY : src/aroma/graph/draw/blur.c.o

src/aroma/graph/draw/blur.i: src/aroma/graph/draw/blur.c.i

.PHONY : src/aroma/graph/draw/blur.i

# target to preprocess a source file
src/aroma/graph/draw/blur.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/blur.c.i
.PHONY : src/aroma/graph/draw/blur.c.i

src/aroma/graph/draw/blur.s: src/aroma/graph/draw/blur.c.s

.PHONY : src/aroma/graph/draw/blur.s

# target to generate assembly for a file
src/aroma/graph/draw/blur.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/blur.c.s
.PHONY : src/aroma/graph/draw/blur.c.s

src/aroma/graph/draw/commondraw.o: src/aroma/graph/draw/commondraw.c.o

.PHONY : src/aroma/graph/draw/commondraw.o

# target to build an object file
src/aroma/graph/draw/commondraw.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/commondraw.c.o
.PHONY : src/aroma/graph/draw/commondraw.c.o

src/aroma/graph/draw/commondraw.i: src/aroma/graph/draw/commondraw.c.i

.PHONY : src/aroma/graph/draw/commondraw.i

# target to preprocess a source file
src/aroma/graph/draw/commondraw.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/commondraw.c.i
.PHONY : src/aroma/graph/draw/commondraw.c.i

src/aroma/graph/draw/commondraw.s: src/aroma/graph/draw/commondraw.c.s

.PHONY : src/aroma/graph/draw/commondraw.s

# target to generate assembly for a file
src/aroma/graph/draw/commondraw.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/commondraw.c.s
.PHONY : src/aroma/graph/draw/commondraw.c.s

src/aroma/graph/draw/filters.o: src/aroma/graph/draw/filters.c.o

.PHONY : src/aroma/graph/draw/filters.o

# target to build an object file
src/aroma/graph/draw/filters.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/filters.c.o
.PHONY : src/aroma/graph/draw/filters.c.o

src/aroma/graph/draw/filters.i: src/aroma/graph/draw/filters.c.i

.PHONY : src/aroma/graph/draw/filters.i

# target to preprocess a source file
src/aroma/graph/draw/filters.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/filters.c.i
.PHONY : src/aroma/graph/draw/filters.c.i

src/aroma/graph/draw/filters.s: src/aroma/graph/draw/filters.c.s

.PHONY : src/aroma/graph/draw/filters.s

# target to generate assembly for a file
src/aroma/graph/draw/filters.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/filters.c.s
.PHONY : src/aroma/graph/draw/filters.c.s

src/aroma/graph/draw/gradient.o: src/aroma/graph/draw/gradient.c.o

.PHONY : src/aroma/graph/draw/gradient.o

# target to build an object file
src/aroma/graph/draw/gradient.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/gradient.c.o
.PHONY : src/aroma/graph/draw/gradient.c.o

src/aroma/graph/draw/gradient.i: src/aroma/graph/draw/gradient.c.i

.PHONY : src/aroma/graph/draw/gradient.i

# target to preprocess a source file
src/aroma/graph/draw/gradient.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/gradient.c.i
.PHONY : src/aroma/graph/draw/gradient.c.i

src/aroma/graph/draw/gradient.s: src/aroma/graph/draw/gradient.c.s

.PHONY : src/aroma/graph/draw/gradient.s

# target to generate assembly for a file
src/aroma/graph/draw/gradient.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/gradient.c.s
.PHONY : src/aroma/graph/draw/gradient.c.s

src/aroma/graph/draw/path.o: src/aroma/graph/draw/path.c.o

.PHONY : src/aroma/graph/draw/path.o

# target to build an object file
src/aroma/graph/draw/path.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/path.c.o
.PHONY : src/aroma/graph/draw/path.c.o

src/aroma/graph/draw/path.i: src/aroma/graph/draw/path.c.i

.PHONY : src/aroma/graph/draw/path.i

# target to preprocess a source file
src/aroma/graph/draw/path.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/path.c.i
.PHONY : src/aroma/graph/draw/path.c.i

src/aroma/graph/draw/path.s: src/aroma/graph/draw/path.c.s

.PHONY : src/aroma/graph/draw/path.s

# target to generate assembly for a file
src/aroma/graph/draw/path.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/path.c.s
.PHONY : src/aroma/graph/draw/path.c.s

src/aroma/graph/draw/scale.o: src/aroma/graph/draw/scale.c.o

.PHONY : src/aroma/graph/draw/scale.o

# target to build an object file
src/aroma/graph/draw/scale.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/scale.c.o
.PHONY : src/aroma/graph/draw/scale.c.o

src/aroma/graph/draw/scale.i: src/aroma/graph/draw/scale.c.i

.PHONY : src/aroma/graph/draw/scale.i

# target to preprocess a source file
src/aroma/graph/draw/scale.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/scale.c.i
.PHONY : src/aroma/graph/draw/scale.c.i

src/aroma/graph/draw/scale.s: src/aroma/graph/draw/scale.c.s

.PHONY : src/aroma/graph/draw/scale.s

# target to generate assembly for a file
src/aroma/graph/draw/scale.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/draw/scale.c.s
.PHONY : src/aroma/graph/draw/scale.c.s

src/aroma/graph/engine/alignblt.o: src/aroma/graph/engine/alignblt.c.o

.PHONY : src/aroma/graph/engine/alignblt.o

# target to build an object file
src/aroma/graph/engine/alignblt.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/alignblt.c.o
.PHONY : src/aroma/graph/engine/alignblt.c.o

src/aroma/graph/engine/alignblt.i: src/aroma/graph/engine/alignblt.c.i

.PHONY : src/aroma/graph/engine/alignblt.i

# target to preprocess a source file
src/aroma/graph/engine/alignblt.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/alignblt.c.i
.PHONY : src/aroma/graph/engine/alignblt.c.i

src/aroma/graph/engine/alignblt.s: src/aroma/graph/engine/alignblt.c.s

.PHONY : src/aroma/graph/engine/alignblt.s

# target to generate assembly for a file
src/aroma/graph/engine/alignblt.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/alignblt.c.s
.PHONY : src/aroma/graph/engine/alignblt.c.s

src/aroma/graph/engine/alpha.o: src/aroma/graph/engine/alpha.c.o

.PHONY : src/aroma/graph/engine/alpha.o

# target to build an object file
src/aroma/graph/engine/alpha.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/alpha.c.o
.PHONY : src/aroma/graph/engine/alpha.c.o

src/aroma/graph/engine/alpha.i: src/aroma/graph/engine/alpha.c.i

.PHONY : src/aroma/graph/engine/alpha.i

# target to preprocess a source file
src/aroma/graph/engine/alpha.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/alpha.c.i
.PHONY : src/aroma/graph/engine/alpha.c.i

src/aroma/graph/engine/alpha.s: src/aroma/graph/engine/alpha.c.s

.PHONY : src/aroma/graph/engine/alpha.s

# target to generate assembly for a file
src/aroma/graph/engine/alpha.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/alpha.c.s
.PHONY : src/aroma/graph/engine/alpha.c.s

src/aroma/graph/engine/blt.o: src/aroma/graph/engine/blt.c.o

.PHONY : src/aroma/graph/engine/blt.o

# target to build an object file
src/aroma/graph/engine/blt.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/blt.c.o
.PHONY : src/aroma/graph/engine/blt.c.o

src/aroma/graph/engine/blt.i: src/aroma/graph/engine/blt.c.i

.PHONY : src/aroma/graph/engine/blt.i

# target to preprocess a source file
src/aroma/graph/engine/blt.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/blt.c.i
.PHONY : src/aroma/graph/engine/blt.c.i

src/aroma/graph/engine/blt.s: src/aroma/graph/engine/blt.c.s

.PHONY : src/aroma/graph/engine/blt.s

# target to generate assembly for a file
src/aroma/graph/engine/blt.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/blt.c.s
.PHONY : src/aroma/graph/engine/blt.c.s

src/aroma/graph/engine/color.o: src/aroma/graph/engine/color.c.o

.PHONY : src/aroma/graph/engine/color.o

# target to build an object file
src/aroma/graph/engine/color.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/color.c.o
.PHONY : src/aroma/graph/engine/color.c.o

src/aroma/graph/engine/color.i: src/aroma/graph/engine/color.c.i

.PHONY : src/aroma/graph/engine/color.i

# target to preprocess a source file
src/aroma/graph/engine/color.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/color.c.i
.PHONY : src/aroma/graph/engine/color.c.i

src/aroma/graph/engine/color.s: src/aroma/graph/engine/color.c.s

.PHONY : src/aroma/graph/engine/color.s

# target to generate assembly for a file
src/aroma/graph/engine/color.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/color.c.s
.PHONY : src/aroma/graph/engine/color.c.s

src/aroma/graph/engine/dither.o: src/aroma/graph/engine/dither.c.o

.PHONY : src/aroma/graph/engine/dither.o

# target to build an object file
src/aroma/graph/engine/dither.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/dither.c.o
.PHONY : src/aroma/graph/engine/dither.c.o

src/aroma/graph/engine/dither.i: src/aroma/graph/engine/dither.c.i

.PHONY : src/aroma/graph/engine/dither.i

# target to preprocess a source file
src/aroma/graph/engine/dither.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/dither.c.i
.PHONY : src/aroma/graph/engine/dither.c.i

src/aroma/graph/engine/dither.s: src/aroma/graph/engine/dither.c.s

.PHONY : src/aroma/graph/engine/dither.s

# target to generate assembly for a file
src/aroma/graph/engine/dither.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/engine/dither.c.s
.PHONY : src/aroma/graph/engine/dither.c.s

src/aroma/graph/fb.o: src/aroma/graph/fb.c.o

.PHONY : src/aroma/graph/fb.o

# target to build an object file
src/aroma/graph/fb.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/fb.c.o
.PHONY : src/aroma/graph/fb.c.o

src/aroma/graph/fb.i: src/aroma/graph/fb.c.i

.PHONY : src/aroma/graph/fb.i

# target to preprocess a source file
src/aroma/graph/fb.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/fb.c.i
.PHONY : src/aroma/graph/fb.c.i

src/aroma/graph/fb.s: src/aroma/graph/fb.c.s

.PHONY : src/aroma/graph/fb.s

# target to generate assembly for a file
src/aroma/graph/fb.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/fb.c.s
.PHONY : src/aroma/graph/fb.c.s

src/aroma/graph/image.o: src/aroma/graph/image.c.o

.PHONY : src/aroma/graph/image.o

# target to build an object file
src/aroma/graph/image.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/image.c.o
.PHONY : src/aroma/graph/image.c.o

src/aroma/graph/image.i: src/aroma/graph/image.c.i

.PHONY : src/aroma/graph/image.i

# target to preprocess a source file
src/aroma/graph/image.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/image.c.i
.PHONY : src/aroma/graph/image.c.i

src/aroma/graph/image.s: src/aroma/graph/image.c.s

.PHONY : src/aroma/graph/image.s

# target to generate assembly for a file
src/aroma/graph/image.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/image.c.s
.PHONY : src/aroma/graph/image.c.s

src/aroma/graph/jpeg.o: src/aroma/graph/jpeg.c.o

.PHONY : src/aroma/graph/jpeg.o

# target to build an object file
src/aroma/graph/jpeg.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/jpeg.c.o
.PHONY : src/aroma/graph/jpeg.c.o

src/aroma/graph/jpeg.i: src/aroma/graph/jpeg.c.i

.PHONY : src/aroma/graph/jpeg.i

# target to preprocess a source file
src/aroma/graph/jpeg.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/jpeg.c.i
.PHONY : src/aroma/graph/jpeg.c.i

src/aroma/graph/jpeg.s: src/aroma/graph/jpeg.c.s

.PHONY : src/aroma/graph/jpeg.s

# target to generate assembly for a file
src/aroma/graph/jpeg.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/jpeg.c.s
.PHONY : src/aroma/graph/jpeg.c.s

src/aroma/graph/png.o: src/aroma/graph/png.c.o

.PHONY : src/aroma/graph/png.o

# target to build an object file
src/aroma/graph/png.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/png.c.o
.PHONY : src/aroma/graph/png.c.o

src/aroma/graph/png.i: src/aroma/graph/png.c.i

.PHONY : src/aroma/graph/png.i

# target to preprocess a source file
src/aroma/graph/png.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/png.c.i
.PHONY : src/aroma/graph/png.c.i

src/aroma/graph/png.s: src/aroma/graph/png.c.s

.PHONY : src/aroma/graph/png.s

# target to generate assembly for a file
src/aroma/graph/png.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/png.c.s
.PHONY : src/aroma/graph/png.c.s

src/aroma/graph/svg.o: src/aroma/graph/svg.c.o

.PHONY : src/aroma/graph/svg.o

# target to build an object file
src/aroma/graph/svg.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/svg.c.o
.PHONY : src/aroma/graph/svg.c.o

src/aroma/graph/svg.i: src/aroma/graph/svg.c.i

.PHONY : src/aroma/graph/svg.i

# target to preprocess a source file
src/aroma/graph/svg.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/svg.c.i
.PHONY : src/aroma/graph/svg.c.i

src/aroma/graph/svg.s: src/aroma/graph/svg.c.s

.PHONY : src/aroma/graph/svg.s

# target to generate assembly for a file
src/aroma/graph/svg.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/svg.c.s
.PHONY : src/aroma/graph/svg.c.s

src/aroma/graph/text.o: src/aroma/graph/text.c.o

.PHONY : src/aroma/graph/text.o

# target to build an object file
src/aroma/graph/text.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/text.c.o
.PHONY : src/aroma/graph/text.c.o

src/aroma/graph/text.i: src/aroma/graph/text.c.i

.PHONY : src/aroma/graph/text.i

# target to preprocess a source file
src/aroma/graph/text.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/text.c.i
.PHONY : src/aroma/graph/text.c.i

src/aroma/graph/text.s: src/aroma/graph/text.c.s

.PHONY : src/aroma/graph/text.s

# target to generate assembly for a file
src/aroma/graph/text.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/graph/text.c.s
.PHONY : src/aroma/graph/text.c.s

src/aroma/hid/hid.o: src/aroma/hid/hid.c.o

.PHONY : src/aroma/hid/hid.o

# target to build an object file
src/aroma/hid/hid.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/hid/hid.c.o
.PHONY : src/aroma/hid/hid.c.o

src/aroma/hid/hid.i: src/aroma/hid/hid.c.i

.PHONY : src/aroma/hid/hid.i

# target to preprocess a source file
src/aroma/hid/hid.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/hid/hid.c.i
.PHONY : src/aroma/hid/hid.c.i

src/aroma/hid/hid.s: src/aroma/hid/hid.c.s

.PHONY : src/aroma/hid/hid.s

# target to generate assembly for a file
src/aroma/hid/hid.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/hid/hid.c.s
.PHONY : src/aroma/hid/hid.c.s

src/aroma/hid/messages.o: src/aroma/hid/messages.c.o

.PHONY : src/aroma/hid/messages.o

# target to build an object file
src/aroma/hid/messages.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/hid/messages.c.o
.PHONY : src/aroma/hid/messages.c.o

src/aroma/hid/messages.i: src/aroma/hid/messages.c.i

.PHONY : src/aroma/hid/messages.i

# target to preprocess a source file
src/aroma/hid/messages.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/hid/messages.c.i
.PHONY : src/aroma/hid/messages.c.i

src/aroma/hid/messages.s: src/aroma/hid/messages.c.s

.PHONY : src/aroma/hid/messages.s

# target to generate assembly for a file
src/aroma/hid/messages.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/hid/messages.c.s
.PHONY : src/aroma/hid/messages.c.s

src/aroma/ui/color_manager.o: src/aroma/ui/color_manager.c.o

.PHONY : src/aroma/ui/color_manager.o

# target to build an object file
src/aroma/ui/color_manager.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/color_manager.c.o
.PHONY : src/aroma/ui/color_manager.c.o

src/aroma/ui/color_manager.i: src/aroma/ui/color_manager.c.i

.PHONY : src/aroma/ui/color_manager.i

# target to preprocess a source file
src/aroma/ui/color_manager.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/color_manager.c.i
.PHONY : src/aroma/ui/color_manager.c.i

src/aroma/ui/color_manager.s: src/aroma/ui/color_manager.c.s

.PHONY : src/aroma/ui/color_manager.s

# target to generate assembly for a file
src/aroma/ui/color_manager.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/color_manager.c.s
.PHONY : src/aroma/ui/color_manager.c.s

src/aroma/ui/control.o: src/aroma/ui/control.c.o

.PHONY : src/aroma/ui/control.o

# target to build an object file
src/aroma/ui/control.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/control.c.o
.PHONY : src/aroma/ui/control.c.o

src/aroma/ui/control.i: src/aroma/ui/control.c.i

.PHONY : src/aroma/ui/control.i

# target to preprocess a source file
src/aroma/ui/control.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/control.c.i
.PHONY : src/aroma/ui/control.c.i

src/aroma/ui/control.s: src/aroma/ui/control.c.s

.PHONY : src/aroma/ui/control.s

# target to generate assembly for a file
src/aroma/ui/control.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/control.c.s
.PHONY : src/aroma/ui/control.c.s

src/aroma/ui/dialog.o: src/aroma/ui/dialog.c.o

.PHONY : src/aroma/ui/dialog.o

# target to build an object file
src/aroma/ui/dialog.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/dialog.c.o
.PHONY : src/aroma/ui/dialog.c.o

src/aroma/ui/dialog.i: src/aroma/ui/dialog.c.i

.PHONY : src/aroma/ui/dialog.i

# target to preprocess a source file
src/aroma/ui/dialog.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/dialog.c.i
.PHONY : src/aroma/ui/dialog.c.i

src/aroma/ui/dialog.s: src/aroma/ui/dialog.c.s

.PHONY : src/aroma/ui/dialog.s

# target to generate assembly for a file
src/aroma/ui/dialog.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/dialog.c.s
.PHONY : src/aroma/ui/dialog.c.s

src/aroma/ui/window.o: src/aroma/ui/window.c.o

.PHONY : src/aroma/ui/window.o

# target to build an object file
src/aroma/ui/window.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window.c.o
.PHONY : src/aroma/ui/window.c.o

src/aroma/ui/window.i: src/aroma/ui/window.c.i

.PHONY : src/aroma/ui/window.i

# target to preprocess a source file
src/aroma/ui/window.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window.c.i
.PHONY : src/aroma/ui/window.c.i

src/aroma/ui/window.s: src/aroma/ui/window.c.s

.PHONY : src/aroma/ui/window.s

# target to generate assembly for a file
src/aroma/ui/window.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window.c.s
.PHONY : src/aroma/ui/window.c.s

src/aroma/ui/window_layer.o: src/aroma/ui/window_layer.c.o

.PHONY : src/aroma/ui/window_layer.o

# target to build an object file
src/aroma/ui/window_layer.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window_layer.c.o
.PHONY : src/aroma/ui/window_layer.c.o

src/aroma/ui/window_layer.i: src/aroma/ui/window_layer.c.i

.PHONY : src/aroma/ui/window_layer.i

# target to preprocess a source file
src/aroma/ui/window_layer.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window_layer.c.i
.PHONY : src/aroma/ui/window_layer.c.i

src/aroma/ui/window_layer.s: src/aroma/ui/window_layer.c.s

.PHONY : src/aroma/ui/window_layer.s

# target to generate assembly for a file
src/aroma/ui/window_layer.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window_layer.c.s
.PHONY : src/aroma/ui/window_layer.c.s

src/aroma/ui/window_manager.o: src/aroma/ui/window_manager.c.o

.PHONY : src/aroma/ui/window_manager.o

# target to build an object file
src/aroma/ui/window_manager.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window_manager.c.o
.PHONY : src/aroma/ui/window_manager.c.o

src/aroma/ui/window_manager.i: src/aroma/ui/window_manager.c.i

.PHONY : src/aroma/ui/window_manager.i

# target to preprocess a source file
src/aroma/ui/window_manager.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window_manager.c.i
.PHONY : src/aroma/ui/window_manager.c.i

src/aroma/ui/window_manager.s: src/aroma/ui/window_manager.c.s

.PHONY : src/aroma/ui/window_manager.s

# target to generate assembly for a file
src/aroma/ui/window_manager.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/ui/window_manager.c.s
.PHONY : src/aroma/ui/window_manager.c.s

src/aroma/utils/array.o: src/aroma/utils/array.c.o

.PHONY : src/aroma/utils/array.o

# target to build an object file
src/aroma/utils/array.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/array.c.o
.PHONY : src/aroma/utils/array.c.o

src/aroma/utils/array.i: src/aroma/utils/array.c.i

.PHONY : src/aroma/utils/array.i

# target to preprocess a source file
src/aroma/utils/array.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/array.c.i
.PHONY : src/aroma/utils/array.c.i

src/aroma/utils/array.s: src/aroma/utils/array.c.s

.PHONY : src/aroma/utils/array.s

# target to generate assembly for a file
src/aroma/utils/array.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/array.c.s
.PHONY : src/aroma/utils/array.c.s

src/aroma/utils/json.o: src/aroma/utils/json.c.o

.PHONY : src/aroma/utils/json.o

# target to build an object file
src/aroma/utils/json.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/json.c.o
.PHONY : src/aroma/utils/json.c.o

src/aroma/utils/json.i: src/aroma/utils/json.c.i

.PHONY : src/aroma/utils/json.i

# target to preprocess a source file
src/aroma/utils/json.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/json.c.i
.PHONY : src/aroma/utils/json.c.i

src/aroma/utils/json.s: src/aroma/utils/json.c.s

.PHONY : src/aroma/utils/json.s

# target to generate assembly for a file
src/aroma/utils/json.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/json.c.s
.PHONY : src/aroma/utils/json.c.s

src/aroma/utils/minutf8.o: src/aroma/utils/minutf8.c.o

.PHONY : src/aroma/utils/minutf8.o

# target to build an object file
src/aroma/utils/minutf8.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/minutf8.c.o
.PHONY : src/aroma/utils/minutf8.c.o

src/aroma/utils/minutf8.i: src/aroma/utils/minutf8.c.i

.PHONY : src/aroma/utils/minutf8.i

# target to preprocess a source file
src/aroma/utils/minutf8.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/minutf8.c.i
.PHONY : src/aroma/utils/minutf8.c.i

src/aroma/utils/minutf8.s: src/aroma/utils/minutf8.c.s

.PHONY : src/aroma/utils/minutf8.s

# target to generate assembly for a file
src/aroma/utils/minutf8.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/minutf8.c.s
.PHONY : src/aroma/utils/minutf8.c.s

src/aroma/utils/motions.o: src/aroma/utils/motions.c.o

.PHONY : src/aroma/utils/motions.o

# target to build an object file
src/aroma/utils/motions.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/motions.c.o
.PHONY : src/aroma/utils/motions.c.o

src/aroma/utils/motions.i: src/aroma/utils/motions.c.i

.PHONY : src/aroma/utils/motions.i

# target to preprocess a source file
src/aroma/utils/motions.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/motions.c.i
.PHONY : src/aroma/utils/motions.c.i

src/aroma/utils/motions.s: src/aroma/utils/motions.c.s

.PHONY : src/aroma/utils/motions.s

# target to generate assembly for a file
src/aroma/utils/motions.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/motions.c.s
.PHONY : src/aroma/utils/motions.c.s

src/aroma/utils/runtime.o: src/aroma/utils/runtime.c.o

.PHONY : src/aroma/utils/runtime.o

# target to build an object file
src/aroma/utils/runtime.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/runtime.c.o
.PHONY : src/aroma/utils/runtime.c.o

src/aroma/utils/runtime.i: src/aroma/utils/runtime.c.i

.PHONY : src/aroma/utils/runtime.i

# target to preprocess a source file
src/aroma/utils/runtime.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/runtime.c.i
.PHONY : src/aroma/utils/runtime.c.i

src/aroma/utils/runtime.s: src/aroma/utils/runtime.c.s

.PHONY : src/aroma/utils/runtime.s

# target to generate assembly for a file
src/aroma/utils/runtime.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/runtime.c.s
.PHONY : src/aroma/utils/runtime.c.s

src/aroma/utils/stream.o: src/aroma/utils/stream.c.o

.PHONY : src/aroma/utils/stream.o

# target to build an object file
src/aroma/utils/stream.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/stream.c.o
.PHONY : src/aroma/utils/stream.c.o

src/aroma/utils/stream.i: src/aroma/utils/stream.c.i

.PHONY : src/aroma/utils/stream.i

# target to preprocess a source file
src/aroma/utils/stream.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/stream.c.i
.PHONY : src/aroma/utils/stream.c.i

src/aroma/utils/stream.s: src/aroma/utils/stream.c.s

.PHONY : src/aroma/utils/stream.s

# target to generate assembly for a file
src/aroma/utils/stream.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/stream.c.s
.PHONY : src/aroma/utils/stream.c.s

src/aroma/utils/strings.o: src/aroma/utils/strings.c.o

.PHONY : src/aroma/utils/strings.o

# target to build an object file
src/aroma/utils/strings.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/strings.c.o
.PHONY : src/aroma/utils/strings.c.o

src/aroma/utils/strings.i: src/aroma/utils/strings.c.i

.PHONY : src/aroma/utils/strings.i

# target to preprocess a source file
src/aroma/utils/strings.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/strings.c.i
.PHONY : src/aroma/utils/strings.c.i

src/aroma/utils/strings.s: src/aroma/utils/strings.c.s

.PHONY : src/aroma/utils/strings.s

# target to generate assembly for a file
src/aroma/utils/strings.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/strings.c.s
.PHONY : src/aroma/utils/strings.c.s

src/aroma/utils/system.o: src/aroma/utils/system.c.o

.PHONY : src/aroma/utils/system.o

# target to build an object file
src/aroma/utils/system.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/system.c.o
.PHONY : src/aroma/utils/system.c.o

src/aroma/utils/system.i: src/aroma/utils/system.c.i

.PHONY : src/aroma/utils/system.i

# target to preprocess a source file
src/aroma/utils/system.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/system.c.i
.PHONY : src/aroma/utils/system.c.i

src/aroma/utils/system.s: src/aroma/utils/system.c.s

.PHONY : src/aroma/utils/system.s

# target to generate assembly for a file
src/aroma/utils/system.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/system.c.s
.PHONY : src/aroma/utils/system.c.s

src/aroma/utils/time.o: src/aroma/utils/time.c.o

.PHONY : src/aroma/utils/time.o

# target to build an object file
src/aroma/utils/time.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/time.c.o
.PHONY : src/aroma/utils/time.c.o

src/aroma/utils/time.i: src/aroma/utils/time.c.i

.PHONY : src/aroma/utils/time.i

# target to preprocess a source file
src/aroma/utils/time.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/time.c.i
.PHONY : src/aroma/utils/time.c.i

src/aroma/utils/time.s: src/aroma/utils/time.c.s

.PHONY : src/aroma/utils/time.s

# target to generate assembly for a file
src/aroma/utils/time.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/time.c.s
.PHONY : src/aroma/utils/time.c.s

src/aroma/utils/zip.o: src/aroma/utils/zip.c.o

.PHONY : src/aroma/utils/zip.o

# target to build an object file
src/aroma/utils/zip.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/zip.c.o
.PHONY : src/aroma/utils/zip.c.o

src/aroma/utils/zip.i: src/aroma/utils/zip.c.i

.PHONY : src/aroma/utils/zip.i

# target to preprocess a source file
src/aroma/utils/zip.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/zip.c.i
.PHONY : src/aroma/utils/zip.c.i

src/aroma/utils/zip.s: src/aroma/utils/zip.c.s

.PHONY : src/aroma/utils/zip.s

# target to generate assembly for a file
src/aroma/utils/zip.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/utils/zip.c.s
.PHONY : src/aroma/utils/zip.c.s

src/aroma/version.o: src/aroma/version.c.o

.PHONY : src/aroma/version.o

# target to build an object file
src/aroma/version.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/version.c.o
.PHONY : src/aroma/version.c.o

src/aroma/version.i: src/aroma/version.c.i

.PHONY : src/aroma/version.i

# target to preprocess a source file
src/aroma/version.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/version.c.i
.PHONY : src/aroma/version.c.i

src/aroma/version.s: src/aroma/version.c.s

.PHONY : src/aroma/version.s

# target to generate assembly for a file
src/aroma/version.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/aroma/version.c.s
.PHONY : src/aroma/version.c.s

src/contrib/platform/linux/fb_driver.o: src/contrib/platform/linux/fb_driver.c.o

.PHONY : src/contrib/platform/linux/fb_driver.o

# target to build an object file
src/contrib/platform/linux/fb_driver.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/fb_driver.c.o
.PHONY : src/contrib/platform/linux/fb_driver.c.o

src/contrib/platform/linux/fb_driver.i: src/contrib/platform/linux/fb_driver.c.i

.PHONY : src/contrib/platform/linux/fb_driver.i

# target to preprocess a source file
src/contrib/platform/linux/fb_driver.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/fb_driver.c.i
.PHONY : src/contrib/platform/linux/fb_driver.c.i

src/contrib/platform/linux/fb_driver.s: src/contrib/platform/linux/fb_driver.c.s

.PHONY : src/contrib/platform/linux/fb_driver.s

# target to generate assembly for a file
src/contrib/platform/linux/fb_driver.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/fb_driver.c.s
.PHONY : src/contrib/platform/linux/fb_driver.c.s

src/contrib/platform/linux/hid_driver.o: src/contrib/platform/linux/hid_driver.c.o

.PHONY : src/contrib/platform/linux/hid_driver.o

# target to build an object file
src/contrib/platform/linux/hid_driver.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/hid_driver.c.o
.PHONY : src/contrib/platform/linux/hid_driver.c.o

src/contrib/platform/linux/hid_driver.i: src/contrib/platform/linux/hid_driver.c.i

.PHONY : src/contrib/platform/linux/hid_driver.i

# target to preprocess a source file
src/contrib/platform/linux/hid_driver.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/hid_driver.c.i
.PHONY : src/contrib/platform/linux/hid_driver.c.i

src/contrib/platform/linux/hid_driver.s: src/contrib/platform/linux/hid_driver.c.s

.PHONY : src/contrib/platform/linux/hid_driver.s

# target to generate assembly for a file
src/contrib/platform/linux/hid_driver.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/hid_driver.c.s
.PHONY : src/contrib/platform/linux/hid_driver.c.s

src/contrib/platform/linux/platform.o: src/contrib/platform/linux/platform.c.o

.PHONY : src/contrib/platform/linux/platform.o

# target to build an object file
src/contrib/platform/linux/platform.c.o:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/platform.c.o
.PHONY : src/contrib/platform/linux/platform.c.o

src/contrib/platform/linux/platform.i: src/contrib/platform/linux/platform.c.i

.PHONY : src/contrib/platform/linux/platform.i

# target to preprocess a source file
src/contrib/platform/linux/platform.c.i:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/platform.c.i
.PHONY : src/contrib/platform/linux/platform.c.i

src/contrib/platform/linux/platform.s: src/contrib/platform/linux/platform.c.s

.PHONY : src/contrib/platform/linux/platform.s

# target to generate assembly for a file
src/contrib/platform/linux/platform.c.s:
	$(MAKE) -f CMakeFiles/aroma.dir/build.make CMakeFiles/aroma.dir/src/contrib/platform/linux/platform.c.s
.PHONY : src/contrib/platform/linux/platform.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libaroma_test"
	@echo "... aroma"
	@echo "... z"
	@echo "... freetype"
	@echo "... harfbuzz"
	@echo "... hbucdn"
	@echo "... minzip"
	@echo "... png"
	@echo "... jpeg"
	@echo "... examples/recovery/recovery.o"
	@echo "... examples/recovery/recovery.i"
	@echo "... examples/recovery/recovery.s"
	@echo "... examples/recovery/recovery_libs.o"
	@echo "... examples/recovery/recovery_libs.i"
	@echo "... examples/recovery/recovery_libs.s"
	@echo "... examples/recovery/recovery_mainmenu.o"
	@echo "... examples/recovery/recovery_mainmenu.i"
	@echo "... examples/recovery/recovery_mainmenu.s"
	@echo "... examples/recovery/recovery_usb.o"
	@echo "... examples/recovery/recovery_usb.i"
	@echo "... examples/recovery/recovery_usb.s"
	@echo "... src/aroma/arch/x86_64/android_memset16.o"
	@echo "... src/aroma/arch/x86_64/android_memset32.o"
	@echo "... src/aroma/aroma.o"
	@echo "... src/aroma/aroma.i"
	@echo "... src/aroma/aroma.s"
	@echo "... src/aroma/controls/ctl_bar.o"
	@echo "... src/aroma/controls/ctl_bar.i"
	@echo "... src/aroma/controls/ctl_bar.s"
	@echo "... src/aroma/controls/ctl_button.o"
	@echo "... src/aroma/controls/ctl_button.i"
	@echo "... src/aroma/controls/ctl_button.s"
	@echo "... src/aroma/controls/ctl_fragment.o"
	@echo "... src/aroma/controls/ctl_fragment.i"
	@echo "... src/aroma/controls/ctl_fragment.s"
	@echo "... src/aroma/controls/ctl_image.o"
	@echo "... src/aroma/controls/ctl_image.i"
	@echo "... src/aroma/controls/ctl_image.s"
	@echo "... src/aroma/controls/ctl_label.o"
	@echo "... src/aroma/controls/ctl_label.i"
	@echo "... src/aroma/controls/ctl_label.s"
	@echo "... src/aroma/controls/ctl_list.o"
	@echo "... src/aroma/controls/ctl_list.i"
	@echo "... src/aroma/controls/ctl_list.s"
	@echo "... src/aroma/controls/ctl_pager.o"
	@echo "... src/aroma/controls/ctl_pager.i"
	@echo "... src/aroma/controls/ctl_pager.s"
	@echo "... src/aroma/controls/ctl_progress.o"
	@echo "... src/aroma/controls/ctl_progress.i"
	@echo "... src/aroma/controls/ctl_progress.s"
	@echo "... src/aroma/controls/ctl_scroll.o"
	@echo "... src/aroma/controls/ctl_scroll.i"
	@echo "... src/aroma/controls/ctl_scroll.s"
	@echo "... src/aroma/controls/ctl_tabs.o"
	@echo "... src/aroma/controls/ctl_tabs.i"
	@echo "... src/aroma/controls/ctl_tabs.s"
	@echo "... src/aroma/controls/listitem/listitem_caption.o"
	@echo "... src/aroma/controls/listitem/listitem_caption.i"
	@echo "... src/aroma/controls/listitem/listitem_caption.s"
	@echo "... src/aroma/controls/listitem/listitem_check.o"
	@echo "... src/aroma/controls/listitem/listitem_check.i"
	@echo "... src/aroma/controls/listitem/listitem_check.s"
	@echo "... src/aroma/controls/listitem/listitem_divider.o"
	@echo "... src/aroma/controls/listitem/listitem_divider.i"
	@echo "... src/aroma/controls/listitem/listitem_divider.s"
	@echo "... src/aroma/controls/listitem/listitem_image.o"
	@echo "... src/aroma/controls/listitem/listitem_image.i"
	@echo "... src/aroma/controls/listitem/listitem_image.s"
	@echo "... src/aroma/controls/listitem/listitem_menu.o"
	@echo "... src/aroma/controls/listitem/listitem_menu.i"
	@echo "... src/aroma/controls/listitem/listitem_menu.s"
	@echo "... src/aroma/controls/listitem/listitem_option.o"
	@echo "... src/aroma/controls/listitem/listitem_option.i"
	@echo "... src/aroma/controls/listitem/listitem_option.s"
	@echo "... src/aroma/debug/compiler_message.o"
	@echo "... src/aroma/debug/compiler_message.i"
	@echo "... src/aroma/debug/compiler_message.s"
	@echo "... src/aroma/debug/memory_tracking.o"
	@echo "... src/aroma/debug/memory_tracking.i"
	@echo "... src/aroma/debug/memory_tracking.s"
	@echo "... src/aroma/graph/artworker.o"
	@echo "... src/aroma/graph/artworker.i"
	@echo "... src/aroma/graph/artworker.s"
	@echo "... src/aroma/graph/canvas.o"
	@echo "... src/aroma/graph/canvas.i"
	@echo "... src/aroma/graph/canvas.s"
	@echo "... src/aroma/graph/draw/blur.o"
	@echo "... src/aroma/graph/draw/blur.i"
	@echo "... src/aroma/graph/draw/blur.s"
	@echo "... src/aroma/graph/draw/commondraw.o"
	@echo "... src/aroma/graph/draw/commondraw.i"
	@echo "... src/aroma/graph/draw/commondraw.s"
	@echo "... src/aroma/graph/draw/filters.o"
	@echo "... src/aroma/graph/draw/filters.i"
	@echo "... src/aroma/graph/draw/filters.s"
	@echo "... src/aroma/graph/draw/gradient.o"
	@echo "... src/aroma/graph/draw/gradient.i"
	@echo "... src/aroma/graph/draw/gradient.s"
	@echo "... src/aroma/graph/draw/path.o"
	@echo "... src/aroma/graph/draw/path.i"
	@echo "... src/aroma/graph/draw/path.s"
	@echo "... src/aroma/graph/draw/scale.o"
	@echo "... src/aroma/graph/draw/scale.i"
	@echo "... src/aroma/graph/draw/scale.s"
	@echo "... src/aroma/graph/engine/alignblt.o"
	@echo "... src/aroma/graph/engine/alignblt.i"
	@echo "... src/aroma/graph/engine/alignblt.s"
	@echo "... src/aroma/graph/engine/alpha.o"
	@echo "... src/aroma/graph/engine/alpha.i"
	@echo "... src/aroma/graph/engine/alpha.s"
	@echo "... src/aroma/graph/engine/blt.o"
	@echo "... src/aroma/graph/engine/blt.i"
	@echo "... src/aroma/graph/engine/blt.s"
	@echo "... src/aroma/graph/engine/color.o"
	@echo "... src/aroma/graph/engine/color.i"
	@echo "... src/aroma/graph/engine/color.s"
	@echo "... src/aroma/graph/engine/dither.o"
	@echo "... src/aroma/graph/engine/dither.i"
	@echo "... src/aroma/graph/engine/dither.s"
	@echo "... src/aroma/graph/fb.o"
	@echo "... src/aroma/graph/fb.i"
	@echo "... src/aroma/graph/fb.s"
	@echo "... src/aroma/graph/image.o"
	@echo "... src/aroma/graph/image.i"
	@echo "... src/aroma/graph/image.s"
	@echo "... src/aroma/graph/jpeg.o"
	@echo "... src/aroma/graph/jpeg.i"
	@echo "... src/aroma/graph/jpeg.s"
	@echo "... src/aroma/graph/png.o"
	@echo "... src/aroma/graph/png.i"
	@echo "... src/aroma/graph/png.s"
	@echo "... src/aroma/graph/svg.o"
	@echo "... src/aroma/graph/svg.i"
	@echo "... src/aroma/graph/svg.s"
	@echo "... src/aroma/graph/text.o"
	@echo "... src/aroma/graph/text.i"
	@echo "... src/aroma/graph/text.s"
	@echo "... src/aroma/hid/hid.o"
	@echo "... src/aroma/hid/hid.i"
	@echo "... src/aroma/hid/hid.s"
	@echo "... src/aroma/hid/messages.o"
	@echo "... src/aroma/hid/messages.i"
	@echo "... src/aroma/hid/messages.s"
	@echo "... src/aroma/ui/color_manager.o"
	@echo "... src/aroma/ui/color_manager.i"
	@echo "... src/aroma/ui/color_manager.s"
	@echo "... src/aroma/ui/control.o"
	@echo "... src/aroma/ui/control.i"
	@echo "... src/aroma/ui/control.s"
	@echo "... src/aroma/ui/dialog.o"
	@echo "... src/aroma/ui/dialog.i"
	@echo "... src/aroma/ui/dialog.s"
	@echo "... src/aroma/ui/window.o"
	@echo "... src/aroma/ui/window.i"
	@echo "... src/aroma/ui/window.s"
	@echo "... src/aroma/ui/window_layer.o"
	@echo "... src/aroma/ui/window_layer.i"
	@echo "... src/aroma/ui/window_layer.s"
	@echo "... src/aroma/ui/window_manager.o"
	@echo "... src/aroma/ui/window_manager.i"
	@echo "... src/aroma/ui/window_manager.s"
	@echo "... src/aroma/utils/array.o"
	@echo "... src/aroma/utils/array.i"
	@echo "... src/aroma/utils/array.s"
	@echo "... src/aroma/utils/json.o"
	@echo "... src/aroma/utils/json.i"
	@echo "... src/aroma/utils/json.s"
	@echo "... src/aroma/utils/minutf8.o"
	@echo "... src/aroma/utils/minutf8.i"
	@echo "... src/aroma/utils/minutf8.s"
	@echo "... src/aroma/utils/motions.o"
	@echo "... src/aroma/utils/motions.i"
	@echo "... src/aroma/utils/motions.s"
	@echo "... src/aroma/utils/runtime.o"
	@echo "... src/aroma/utils/runtime.i"
	@echo "... src/aroma/utils/runtime.s"
	@echo "... src/aroma/utils/stream.o"
	@echo "... src/aroma/utils/stream.i"
	@echo "... src/aroma/utils/stream.s"
	@echo "... src/aroma/utils/strings.o"
	@echo "... src/aroma/utils/strings.i"
	@echo "... src/aroma/utils/strings.s"
	@echo "... src/aroma/utils/system.o"
	@echo "... src/aroma/utils/system.i"
	@echo "... src/aroma/utils/system.s"
	@echo "... src/aroma/utils/time.o"
	@echo "... src/aroma/utils/time.i"
	@echo "... src/aroma/utils/time.s"
	@echo "... src/aroma/utils/zip.o"
	@echo "... src/aroma/utils/zip.i"
	@echo "... src/aroma/utils/zip.s"
	@echo "... src/aroma/version.o"
	@echo "... src/aroma/version.i"
	@echo "... src/aroma/version.s"
	@echo "... src/contrib/platform/linux/fb_driver.o"
	@echo "... src/contrib/platform/linux/fb_driver.i"
	@echo "... src/contrib/platform/linux/fb_driver.s"
	@echo "... src/contrib/platform/linux/hid_driver.o"
	@echo "... src/contrib/platform/linux/hid_driver.i"
	@echo "... src/contrib/platform/linux/hid_driver.s"
	@echo "... src/contrib/platform/linux/platform.o"
	@echo "... src/contrib/platform/linux/platform.i"
	@echo "... src/contrib/platform/linux/platform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

